### ISSUE TITLE
ERROR distant version 0.20.0-alpha.10 incompatible with minimum requirement of 0.20.0

### ISSUE THREAD

**Issue by weberam2** [chipsenkbeil/distant.nvim#135]
I'm using Ubuntu 22.04
LazyVim
NVIM v0.10.0-dev-777+gc6c21db82      
Build type: Release                  
LuaJIT 2.1.0-beta3                   

Running DistantHealth I get:
```
distant: require("distant.health").check()

distant.nvim ~
- OK distant installed
- ERROR distant version 0.20.0-alpha.10 incompatible with minimum requirement of 0.20.0
```

I installed by pressing 1 every time...
But there weren't any options to not download the alpha.

Any ideas?

**Comment by evageq** [comment]
Try to install distant from binary (3rd option). Download the binary from https://distant.dev/editors/neovim/installation/#available-binaries, issue :DistantInstall -> choose 3rd option -> specify the location of the downloaded binary.

**Comment by chipsenkbeil** [comment]
There was an issue where installing the distant binary via `:DistantInstall` using the pre-built binary was selecting the wrong version (the alpha) instead of the correct version (the official release). This has been resolved by https://github.com/chipsenkbeil/distant.nvim/commit/823267cf3b77cf9a7ae28454926eabc18fec1ba0.
