### ISSUE TITLE
Pass options to DistantLaunch

### ISSUE THREAD

**Issue by augustebaum** [chipsenkbeil/distant.nvim#31]
Something like `:DistantLaunch example.com -u user`, which I need to log into my remote machine. The shell command does this, so why not the wrapper? Or maybe I've missed something?

**Comment by chipsenkbeil** [comment]
@augustebaum thought I had configured it to support this, but turns out it wasn't set up correctly for DistantLaunch.

Fixed with https://github.com/chipsenkbeil/distant.nvim/commit/3d8a6a42fd438026a3c49513eb42518b8480ae47 where you can now run `:DistantLaunch example.com username=user`. You have to provide the full argument name (not the shorthand) to do this.

Alternatively, you can always call `:lua require('distant').editor.launch(...)` and pass it the arguments you want since `DistantLaunch` is just a wrapper for that lua function.

**Comment by chipsenkbeil** [comment]
Closing this out, but feel free to comment if you have additional questions about the launch command.
