### ISSUE TITLE
:DistantLaunch command fails

### ISSUE THREAD

**Issue by JulienLecoq** [chipsenkbeil/distant.nvim#54]
When I try to start distant with the command ":DistantLaunch 127.0.0.1", I got this error:

![distant_launch_errors](https://user-images.githubusercontent.com/54070985/139910420-850dc74f-60ae-4498-b307-9efb9fa19959.png)

The plugin ask successfully for the password, but crashes just after.
I'm using Ubuntu 20.04.3 LTS and have installed distant.nvim with the option "1. Download a prebuilt lib" and choosed the version "1. v0.15.0".

**Comment by chipsenkbeil** [comment]
Seems like an issue with our underlying ssh client library.

@wez, have you seen this error before when using `ssh2-rs`?

**Comment by chipsenkbeil** [comment]
@JulienLecoq for the time being, until we figure out some of these ssh issues and what workarounds/fixes can be made on the Rust side, you can use the newly-added `DistantConnect` command available in https://github.com/chipsenkbeil/distant.nvim/commit/06de9e1d2203880d99aeb8cbcc9716a3dbe33e1f.

You would need to start the distant server yourself via something like `distant listen --host any` on the server you want to connect to. Then copy the key and port to supply when you connect.

**Comment by JulienLecoq** [comment]
@chipsenkbeil Thanks for the response! 

I now have the newly-added command `DistantConnect` but I do not have the command `distant` in the terminal. Should this command be available after the installation of **distant.nvim**? Or do I have to add it to the **PATH** after the installation?

**Comment by chipsenkbeil** [comment]
@JulienLecoq `DistantConnect` is used to have neovim connect to a running server on your remote machine. You need to start that server yourself whereas `DistantLaunch` attempts to start the server for you. 😄 You will need to have `distant` (the CLI binary) on that machine and start it by using `distant listen --host any`.

`DistantLaunch` also provides an alternative mode where it connects and communicates with the remote server using only ssh, but since your issue is with ssh, that isn't an option for you! That's why I recommended connecting to a running distant server. 😄 

You don't actually need the server on your path. All you need to do is be able to start it and see which port it attaches to and the key that it generates for you.

The distant binary won't be on your machine after you run `DistantInstall` as you only need that binary on the server you want to connect to. In your case, since you are connecting to your own machine using `127.0.0.1`, you will also need the distant binary running on your local machine.

**Comment by JulienLecoq** [comment]
@chipsenkbeil Thanks for your great explanations, I installed the distant binary and now it works perfectly when started manually 😃.

I was wondering where I could get this binary but it is one of your repo haha, here it is for those who are searching for it:
https://github.com/chipsenkbeil/distant
