### ISSUE TITLE
DistantLaunch callback error

### ISSUE THREAD

**Issue by RasmusBertell** [chipsenkbeil/distant.nvim#61]
Running `DistantLaunch <address>` gives the following error

```
SSH-2.0-OpenSSH_7.6p1 Ubuntu-4ubuntu0.5
callback error
stack traceback:
^I[C]: in ?
^I[C]: in function 'pcall'
^I.../packer/start/distant.nvim/lua/distant/editor/launch.lua:81: in function 'load'
^I.../packer/start/distant.nvim/lua/distant/editor/launch.lua:67: in function 'launch'
^I...e/pack/packer/start/distant.nvim/lua/distant/command.lua:177: in function 'launch'
^I[string ":lua"]:1: in main chunk
caused by: deadline has elapsed
callback error
stack traceback:
^I[C]: in ?
^I[C]: in function 'pcall'
^I.../packer/start/distant.nvim/lua/distant/editor/launch.lua:81: in function 'load'
^I.../packer/start/distant.nvim/lua/distant/editor/launch.lua:67: in function 'launch'
^I...e/pack/packer/start/distant.nvim/lua/distant/command.lua:177: in function 'launch'
^I[string ":lua"]:1: in main chunk
caused by: deadline has elapsed
Press ENTER or type command to continue
```

Distant is installed locally and on my remote through cargo and I have minimal config for distant.nvim copied from readme.
I had some errors with `DistantInstall` but after restarting whole computer it seemed to run to completion.

**Comment by RasmusBertell** [comment]
Distant is version 0.15.1 on both machines and NeoVim is version 0.6.0.

**Comment by chipsenkbeil** [comment]
@RasmusBertell I'm seeing a message about a deadline having elapsed. Can you try increasing the max timeout that's mentioned here? https://github.com/chipsenkbeil/distant.nvim/blob/master/doc/distant.txt#L225

Can be done either via a setting in your config or explicitly specifying it when using `:DistantLaunch {host} timeout=30000`

**Comment by RasmusBertell** [comment]
It still gives the same error message when explicitly specifying it. Didnät try to change configuration.

The distant server seems to launch with the command as it spawns a new distant process on the server.
I tried to use distant from command line but there seemed to be some problems also. I could spawn the process but trying some actions fails for some reason.

```
~
❯ distant launch dev

~
❯ distant action copy ~/tmp ~/tmp2
ERROR [distant] Exiting due to error: No such file or directory (os error 2)

~
❯ distant action copy /home/users/rasmus/tmp /home/users/rasmus/tmp2
ERROR [distant] Exiting due to error: No such file or directory (os error 2)
```

**Comment by RasmusBertell** [comment]
Actually it's not quite the same error there's something about connection time out.

```
SSH-2.0-OpenSSH_7.6p1 Ubuntu-4ubuntu0.5
callback error
stack traceback:
^I[C]: in ?
^I[C]: in function 'pcall'
^I.../packer/start/distant.nvim/lua/distant/editor/launch.lua:81: in function 'load'
^I.../packer/start/distant.nvim/lua/distant/editor/launch.lua:67: in function 'launch'

^I...e/pack/packer/start/distant.nvim/lua/distant/command.lua:177: in function 'launch
'
^I[string ":lua"]:1: in main chunk
caused by: Connection timed out (os error 110)
callback error
stack traceback:
^I[C]: in ?
^I[C]: in function 'pcall'
^I.../packer/start/distant.nvim/lua/distant/editor/launch.lua:81: in function 'load'
^I.../packer/start/distant.nvim/lua/distant/editor/launch.lua:67: in function 'launch'

^I...e/pack/packer/start/distant.nvim/lua/distant/command.lua:177: in function 'launch
'
^I[string ":lua"]:1: in main chunk
caused by: Connection timed out (os error 110)
Press ENTER or type command to continue
```

**Comment by chipsenkbeil** [comment]
The new error about connection timed out implies to me that attempting to connect over TCP to the spawned distant server is failing. Since it's an OS-level connection timeout, I think that implies a failure to connect.

You said that you were unable to connect with the cli as well, right? When you run `distant launch ...` on Mac & Linux, this will spawn a daemon that lives on your local machine and acts as a proxy to talk to the remote machine. You communicate over a unix socket, so errors about "no such file or directory" implies that the unix socket is missing for some reason.

The simplest approach is to take out ssh from the equation. Can you try the following for me?

1. Run `distant listen --foreground --host any --log-level trace` on the remote machine. It should print out the port and key you'll need for the client
![image](https://user-images.githubusercontent.com/2481802/145477506-9dd98b99-907d-46ff-b1a5-faf1882a4b1d.png)

2. Create a file somewhere on your machine (maybe in /tmp) to house the connection information. It's in the form of `DISTANT CONNECT {IP} {PORT} {KEY}`
![image](https://user-images.githubusercontent.com/2481802/145478038-0df065cf-34d5-41e0-8e4d-432b14331395.png)

3. Run `distant action --session file --session-file /tmp/my.session dir-read .` or some other action to see if it succeeds.
![image](https://user-images.githubusercontent.com/2481802/145478302-3968ff16-cd07-48ea-9e11-48296b1f5e58.png)

**Comment by RasmusBertell** [comment]
It gives me a connection timeout.

```
~ ❯ distant action --session file --session-file /tmp/my.session dir-read .
ERROR [distant] Exiting due to error: Connection timed out (os error 110)
```

I thought distant used ssh to communicate, but does the new bound port (8080) have to be open to public?
The server I'm connecting to may have all but ssh and https ports closed for outside connections, I'll have to check with the admin.

**Comment by chipsenkbeil** [comment]
@RasmusBertell by default, distant connects over TCP to a server. SSH is only used to spawn the server.

However, you can use ssh mode instead, and distant.nvim will maintain an ssh connection to perform all of the actions without need of the distant server or other ports being exposed.

```
:DistantLaunch example.com mode=ssh ssh.user=name ssh.port=2222
```

**Comment by RasmusBertell** [comment]
Sorry, I misunderstood how it works. I'll close this as it's not a problem with distant.
I had a problem with SSH mode and lsp but that might be just my configuration, I'll open a new issue for it if I decide to go that route and the server admin doesn't want to open the TCP ports.

Thank you for the help and this plugin. I much rather use NeoVim than VSCode when remote editing and I have little control over the server environment so SSHing to the server and installing plugins remotely isn't an option.
