### ISSUE TITLE
:DistantOpen is hanging when using distant binary

### ISSUE THREAD

**Issue by luanzeba** [chipsenkbeil/distant.nvim#70]
I'm not able to open files using `:DistantOpen` after initiating a session with `:DistantLaunch` using the distant binary. It seems to just hang indefinitely without anything noticeable happening and without generating any logs.
I recorded the behavior below and showed that `:DistantOpen` works in ssh mode (sorry about the small font). By the way, after I recorded it, I also tried with `--log-level=debug` and `--log-level=trace` and nothing came up in the logs either.

https://user-images.githubusercontent.com/20481048/174680948-c986bfe7-64f9-49ca-81a5-bf444a5edf92.mp4

Let me know if there's any other information that would be helpful or any steps I can take to troubleshoot

**Comment by chipsenkbeil** [comment]
Whoops, didn't realize this bug was opened. The distant binary is due for a large release in the next day or two, but the plugin needs to be updated to support those changes. I'm hopeful that hanging like this with the distant binary will either not happen or properly get logged. Stay tuned for the 0.17 release of distant and associated plugin update.

**Comment by chipsenkbeil** [comment]
Closing out as an outdated issue. With v0.3 being the new branch that is using distant 0.20.0, feel free to open a new issue against it if this is still a problem.
