### ISSUE TITLE
Mention distant 0.16.0+ incompatability

### ISSUE THREAD

**Issue by Supreeeme** [chipsenkbeil/distant.nvim#71]
Giving this plugin a try and was confused trying to set it up when I came to the realization that there is a branch for distant 0.16. While I couldn't get that to work, I did manage to get distant 0.15 working with the master branch. I think many would appreciate if there was some sort of notice in the README or even a GitHub issue for breaking changes like I've seen a lot of plugins do.

**Comment by chipsenkbeil** [comment]
Good callout. There's a branch that supports 0.16 that introduces a better compatibility check to enforce proper semantic versioning (meaning that 0.16 is not compatible with 0.15 or 0.17). The distant binary ended up getting rewritten and is soon to be released as 0.17, which means the plugin will be updated to support 0.17 instead of 0.16.

When that release happens, the README will also be reflected to update that. In the meantime, I can add a disclaimer to the README in the master branch.

**Comment by chipsenkbeil** [comment]
Disclaimer added.
